### ISSUE TITLE
Back end profile rewritten

### ISSUE THREAD

**Issue by Josh1711** [lanternbox/exploreCRS#16]
Hi,

I have just been going through my candidates to export to PDF and haven't had a problem. However, just now I exported Pamela Thwaites profile (ID 753) and then went to her husbands profile Gideon Thwaites (ID 627). However, when I went to Gideon's profile, all of the information had been copied from Pamela's profile, including the email and password, picture, but not the CV. All of Gideon's information is now his wife's which is very strange as the profiles have been active for ages and haven't had any problems. I began changing it back a bit so the name and the summary are now different so I can see the difference. Please have a look and let me know.

![image](https://cloud.githubusercontent.com/assets/23716044/20913233/f3426204-bbb0-11e6-9c95-29749a1cc8a0.png)

![image](https://cloud.githubusercontent.com/assets/23716044/20913235/f955fb88-bbb0-11e6-8818-e39a7339bce9.png)
![image](https://cloud.githubusercontent.com/assets/23716044/20913248/03379f3a-bbb1-11e6-9941-ec322275b71b.png)

![image](https://cloud.githubusercontent.com/assets/23716044/20913254/0ed671e0-bbb1-11e6-9f06-a658e5444fa9.png)
![image](https://cloud.githubusercontent.com/assets/23716044/20913257/124b8036-bbb1-11e6-9f39-b057a3d58220.png)
![image](https://cloud.githubusercontent.com/assets/23716044/20913260/175a6c90-bbb1-11e6-92c7-16e76b8ae648.png)

**Comment by lantern-andrew** [comment]
Hi Josh,

Thanks for the ticket. I reviewed your screenshots and checked the database, and found the situation appeared as you described.

The candidate profiles are programmed so that within one web browser, only one candidate can be logged in once. (Editing a profile in the CMS is considered a login.) Here is a possible scenario that could have caused the issue:
1) in tab 1, log in as candidate 1 (cand. 1 is now logged in), leave the tab open
2) in tab 2, log in as candidate 2 (cand. 2 is now logged in)
3) return to tab 1 and save the data there (actually cand. 2 is still logged in)

We don't have any way to check records to see if this is exactly what happened, but as far as I can imagine, it seems the most likely possibility.

Sorry for the extra work on your part reentering data  - and if you could, please be wary of the situation described above.

If this issue comes up again in the future, we'll review with Naomi and Vanessa about patching it.

Thanks,
Andrew

**Comment by Josh1711** [comment]
Hi Andrew,

Seems that you may have been correct with that. I did have both the two candidate profiles open because they are a teaching couple. It is easier to have them both active when doing the profiles, exporting them etc. as they are together so it can be more convenient to view it at the same time. I understand now that we can't do that so I have told others also. Thanks.

Josh
